externalLinks:
    redis:
        host: '127.0.0.1'
        port: 6379
        # blank if none
        user: ""
        password: ""
    other:
        serverName: "regl"
        webServerHostName: "regal.pw"
database:
    host: '127.0.0.1'
    port: '3306'
    database: 'ABPromoter'
    user: 'user'
    pass: 'pass'